"""Generate the Homebrew formula, resources and all.

Homebrew builds a Python CLI into its own virtualenv from *sdists it has
hashed*, so every transitive dependency needs a `resource` block with a URL and
a sha256. Hand-maintaining ~30 of those across releases is how a tap rots, so
this reads the resolved set and asks PyPI for the rest.

Run after a release, once the new version is on PyPI:

    uv run python scripts/brew_formula.py --version 0.2.83 > Formula/anime-sh.rb
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Homebrew ships its own Python and these come from it or from brew formulae;
# bundling them as resources either fails to build or duplicates the system.
SKIP = {"anime-sh"}


def resolved(extra: str) -> list[tuple[str, str]]:
    """(name, version) for every dependency, from the project's own resolver."""
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "reqs.txt"
        subprocess.run(
            ["uv", "pip", "compile", str(ROOT / "pyproject.toml"),
             "--extra", extra, "-o", str(out), "-q"],
            check=True, capture_output=True,
        )
        text = out.read_text(encoding="utf-8")
    pairs = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^([A-Za-z0-9._-]+)==([^\s;]+)", line)
        if m and m.group(1).lower() not in SKIP:
            pairs.append((m.group(1), m.group(2)))
    return pairs


def sdist(name: str, version: str) -> tuple[str, str] | None:
    """The sdist URL and sha256 for one pinned release, or None if it has no
    sdist (a wheel-only project cannot be a Homebrew resource)."""
    url = f"https://pypi.org/pypi/{name}/{version}/json"
    with urllib.request.urlopen(url, timeout=30) as resp:
        data = json.load(resp)
    for entry in data["urls"]:
        if entry["packagetype"] == "sdist":
            return entry["url"], entry["digests"]["sha256"]
    return None


def main() -> int:
    # `brew audit` rejects a formula that is not valid UTF-8, and redirecting
    # this script's output on Windows otherwise encodes it as cp1252 - which
    # turned one em dash in a comment into an invalid byte sequence.
    sys.stdout.reconfigure(encoding="utf-8", newline="\n")
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", required=True)
    ap.add_argument("--extra", default="tui")
    args = ap.parse_args()

    main_sdist = sdist("anime-sh", args.version)
    if main_sdist is None:
        print(f"anime-sh {args.version} has no sdist on PyPI", file=sys.stderr)
        return 1
    url, sha = main_sdist

    resources, skipped = [], []
    for name, version in resolved(args.extra):
        found = sdist(name, version)
        if found is None:
            skipped.append(f"{name}=={version}")
            continue
        resources.append((name, version, *found))

    if skipped:
        # Wheel-only dependencies cannot be resources; say so rather than
        # emitting a formula that fails to build with no explanation.
        print("no sdist on PyPI for: " + ", ".join(skipped), file=sys.stderr)

    lines = [
        "# Generated by scripts/brew_formula.py - regenerate after each release.",
        "class AnimeSh < Formula",
        '  include Language::Python::Virtualenv',
        "",
        '  desc "Watch anime from your terminal"',
        '  homepage "https://github.com/Anime123450/anime-sh"',
        f'  url "{url}"',
        f'  sha256 "{sha}"',
        '  license "MIT"',
        "",
        # `brew audit` requires dependencies in alphabetical order.
        "  # mpv plays the video, so it is a hard dependency. ffmpeg is only",
        "  # needed by `anime download`, and it is a heavy install. Homebrew",
        "  # dropped formula options, so it is a caveat rather than an optional.",
        '  depends_on "mpv"',
        '  depends_on "python@3.12"',
        "",
    ]
    for name, version, res_url, res_sha in resources:
        lines += [
            f'  resource "{name}" do',
            f'    url "{res_url}"',
            f'    sha256 "{res_sha}"',
            "  end",
            "",
        ]
    lines += [
        "  def install",
        "    virtualenv_install_with_resources",
        "  end",
        "",
        "  def caveats",
        "    <<~EOS",
        "      Downloads (`anime download`, `anime prefetch`) also need ffmpeg:",
        "        brew install ffmpeg",
        "      Run `anime doctor` to check everything at once.",
        "    EOS",
        "  end",
        "",
        "  test do",
        "    # Proves the entry point exists and the venv imports cleanly, which",
        "    # is what actually breaks when a resource is missing.",
        '    assert_match "anime-sh #{version}", shell_output("#{bin}/anime --version")',
        '    system bin/"anime", "doctor"',
        "  end",
        "end",
    ]
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
